<?php
require_once('config.php');
$link['INDEX'] = $config['site_url'];
$link['HOME'] = $config['site_url'] . 'home';
$link['INDEX_PAGE'] = $config['site_url'] . 'index';
$link['INDEX1'] = $config['site_url'] . 'index1';
$link['INDEX2'] = $config['site_url'] . 'index2';
$link['MESSAGE'] = $config['site_url'] . 'message';
$link['LOGIN'] = $config['site_url'] . 'login';
$link['LOGOUT'] = $config['site_url'] . 'logout';
$link['SIGNUP'] = $config['site_url'] . 'signup';
$link['FORGOT'] = $config['site_url'] . 'forgot';
$link['LISTING'] = $config['site_url'] . 'listing';
$link['JOB_SEEKERS'] = $config['site_url'] . 'job-seekers';
$link['POST-DETAIL'] = $config['site_url'] . 'job';
$link['COMPANY-DETAIL'] = $config['site_url'] . 'company';
$link['POST-JOB'] = $config['site_url'] . 'post-job';
$link['EDIT-JOB'] = $config['site_url'] . 'edit-job';
$link['MYJOBS'] = $config['site_url'] . 'my-jobs';
$link['MYCOMPANIES'] = $config['site_url'] . 'my-companies';
$link['CREATE-COMPANY'] = $config['site_url'] . 'create-company';
$link['EDIT-COMPANY'] = $config['site_url'] . 'edit-company';
$link['EXPERIENCES'] = $config['site_url'] . 'edit-profile/my-experiences';
$link['ADD_EXPERIENCE'] = $config['site_url'] . 'add-experience';
$link['EDIT_EXPERIENCE'] = $config['site_url'] . 'edit-experience';
$link['RESUMES'] = $config['site_url'] . 'my-resumes';
$link['ADD-RESUME'] = $config['site_url'] . 'add-resume';
$link['EDIT-RESUME'] = $config['site_url'] . 'edit-resume';
$link['JOBALERT'] = $config['site_url'] . 'job-alert';
$link['PENDINGJOBS'] = $config['site_url'] . 'pending';
$link['EXPIREJOBS'] = $config['site_url'] . 'expire';
$link['FAVJOBS'] = $config['site_url'] . 'favourite';
$link['FAVUSERS'] = $config['site_url'] . 'favourite-users';
$link['APPLIED_JOBS'] = $config['site_url'] . 'applied-jobs';
$link['APPLIED_USERS'] = $config['site_url'] . 'applied-users';
$link['HIDDENJOBS'] = $config['site_url'] . 'hidden';
$link['RESUBMITJOBS'] = $config['site_url'] . 'resubmission';
$link['DASHBOARD'] = $config['site_url'] . 'dashboard';
$link['PROFILE'] = $config['site_url'] . 'profile';
$link['TRANSACTION'] = $config['site_url'] . 'transaction';
$link['EDIT-PROFILE'] = $config['site_url'] . 'profile-edit';
$link['REPORT'] = $config['site_url'] . 'report';
$link['CONTACT'] = $config['site_url'] . 'contact';
$link['SITEMAP'] = $config['site_url'] . 'sitemap';
$link['COUNTRY'] = $config['site_url'] . 'countries';
$link['COMPANIES'] = $config['site_url'] . 'companies';
$link['BLOG'] = $config['site_url'] . 'blog';
$link['TESTIMONIALS'] = $config['site_url'] . 'testimonials';
$link['BLOG-SINGLE'] = $config['site_url'] . 'blog';
$link['BLOG-CAT'] = $config['site_url'] . 'blog/category';
$link['BLOG-AUTHOR'] = $config['site_url'] . 'blog/author';
$link['FAQ'] = $config['site_url'] . 'faq';
$link['FEEDBACK'] = $config['site_url'] . 'feedback';
$link['COUNTRIES'] = $config['site_url'] . 'countries';
$link['HTML'] = $config['site_url'] . 'html';
$link['MEMBERSHIP'] = $config['site_url'] . 'membership';
$link['PAYMENT'] = $config['site_url'] . 'payment';
$link['IPN'] = $config['site_url'] . 'ipn';
$link['EDITPROFILE'] = $config['site_url'] . 'edit-profile';
$link['BANK_DETAILS'] = $config['site_url'] . 'edit-profile/bank-account';
$link['RATE_AVAILABILITY'] = $config['site_url'] . 'edit-profile/rate-and-availability';
$link['LANGUAGES'] = $config['site_url'] . 'edit-profile/languages';
$link['CULTURAL_BACKGROUNDS'] = $config['site_url'] . 'edit-profile/cultural-backgrounds';
$link['RELIGION'] = $config['site_url'] . 'edit-profile/religion';
$link['EDUCATIONS'] = $config['site_url'] . 'edit-profile/my-educations';
$link['ADD_EDUCATION'] = $config['site_url'] . 'edit-profile/add-education';
$link['EDIT_EDUCATION'] = $config['site_url'] . 'edit-profile/edit-education';
$link['SKILLS'] = $config['site_url'] . 'edit-profile/my-skills';
$link['USER_CUSTOM_FIELDS'] = $config['site_url'] . 'edit-profile/user-custom-fields';
$link['IMMUNISATION_INFO'] = $config['site_url'] . 'edit-profile/immunisation-info';
$link['ABOUT_ME'] = $config['site_url'] . 'edit-profile/about-me';
$link['PREFERENCE'] = $config['site_url'] . 'edit-profile/preference';

$link['MY_DOCUMENTS'] = $config['site_url'] . 'my-documents';
$link['ADD_USER_DOCUMENT'] = $config['site_url'] . 'add-document';
$link['EDIT_DOCUMENT'] = $config['site_url'] . 'edit-document';

// Will Edit
$link['ACCOUNT'] = $config['site_url'] . 'edit-profile/account';
$link['ACCEPTED_JOBS'] = $config['site_url'] . 'accepted-jobs';
$link['REVIEW'] = $config['site_url'] . 'reviews';
$link['INVOICE'] = $config['site_url'] . 'invoices';
$link['TIMESHEET'] = $config['site_url'] . 'timesheets';
$link['ADD_SHIFT'] = $config['site_url'] . 'timesheet/add-shift';
$link['EDIT_SHIFT'] = $config['site_url'] . 'timesheet/edit-shift';

$link['CONVERSATION_STARTER'] = $config['site_url'] . 'conversation-starter';
$link['MYCLIENTS'] = $config['site_url'] . 'my-clients';



$link['WALLET'] = $config['site_url'] . 'wallet';
$link['CREATE_WALLET'] = $config['site_url'] . 'create-wallet';
